# Generated by Django 4.2.4 on 2024-04-14 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftgallery', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
