# Generated by Django 4.2.4 on 2024-04-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftgallery', '0006_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
