# Generated by Django 4.2.4 on 2024-04-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftgallery', '0008_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Front',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='uploads/products/')),
            ],
        ),
    ]
